blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/<YOUR_ORG>/<YOUR_REPO>/security/advisories
    about: Please report security issues privately.
